<?php

use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->insert([
            [
                'numeric_code' => 4,
                'alpha-2_code' => 'AF',
                'alpha-3_code' => 'AFG',
                'display' => json_encode(['en-us' => 'Afghanistan', 'zh-tw' => '阿富汗']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 248,
                'alpha-2_code' => 'AX',
                'alpha-3_code' => 'ALA',
                'display' => json_encode(['en-us' => 'Åland Islands', 'zh-tw' => '奧蘭']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 8,
                'alpha-2_code' => 'AL',
                'alpha-3_code' => 'ALB',
                'display' => json_encode(['en-us' => 'Albania', 'zh-tw' => '阿爾巴尼亞']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 12,
                'alpha-2_code' => 'DZ',
                'alpha-3_code' => 'DZA',
                'display' => json_encode(['en-us' => 'Algeria', 'zh-tw' => '阿爾及利亞']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 16,
                'alpha-2_code' => 'AS',
                'alpha-3_code' => 'ASM',
                'display' => json_encode(['en-us' => 'American Samoa', 'zh-tw' => '美屬薩摩亞']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 20,
                'alpha-2_code' => 'AD',
                'alpha-3_code' => 'AND',
                'display' => json_encode(['en-us' => 'Andorra', 'zh-tw' => '安道爾']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 24,
                'alpha-2_code' => 'AO',
                'alpha-3_code' => 'AGO',
                'display' => json_encode(['en-us' => 'Angola', 'zh-tw' => '安哥拉']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 660,
                'alpha-2_code' => 'AI',
                'alpha-3_code' => 'AIA',
                'display' => json_encode(['en-us' => 'Anguilla', 'zh-tw' => '安圭拉']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 10,
                'alpha-2_code' => 'AQ',
                'alpha-3_code' => 'ATA',
                'display' => json_encode(['en-us' => 'Antarctica', 'zh-tw' => '南極洲']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 28,
                'alpha-2_code' => 'AG',
                'alpha-3_code' => 'ATG',
                'display' => json_encode(['en-us' => 'Antigua and Barbuda', 'zh-tw' => '安地卡及巴布達']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 32,
                'alpha-2_code' => 'AR',
                'alpha-3_code' => 'ARG',
                'display' => json_encode(['en-us' => 'Argentina', 'zh-tw' => '阿根廷']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 51,
                'alpha-2_code' => 'AM',
                'alpha-3_code' => 'ARM',
                'display' => json_encode(['en-us' => 'Armenia', 'zh-tw' => '亞美尼亞']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 533,
                'alpha-2_code' => 'AW',
                'alpha-3_code' => 'ABW',
                'display' => json_encode(['en-us' => 'Aruba', 'zh-tw' => '阿魯巴']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 36,
                'alpha-2_code' => 'AU',
                'alpha-3_code' => 'AUS',
                'display' => json_encode(['en-us' => 'Australia', 'zh-tw' => '澳大利亞']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 40,
                'alpha-2_code' => 'AT',
                'alpha-3_code' => 'AUT',
                'display' => json_encode(['en-us' => 'Austria', 'zh-tw' => '奧地利']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 31,
                'alpha-2_code' => 'AZ',
                'alpha-3_code' => 'AZE',
                'display' => json_encode(['en-us' => 'Azerbaijan', 'zh-tw' => '亞塞拜然']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 44,
                'alpha-2_code' => 'BS',
                'alpha-3_code' => 'BHS',
                'display' => json_encode(['en-us' => 'Bahamas', 'zh-tw' => '巴哈馬']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 48,
                'alpha-2_code' => 'BH',
                'alpha-3_code' => 'BHR',
                'display' => json_encode(['en-us' => 'Bahrain', 'zh-tw' => '巴林']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 50,
                'alpha-2_code' => 'BD',
                'alpha-3_code' => 'BGD',
                'display' => json_encode(['en-us' => 'Bangladesh', 'zh-tw' => '孟加拉國']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 52,
                'alpha-2_code' => 'BB',
                'alpha-3_code' => 'BRB',
                'display' => json_encode(['en-us' => 'Barbados', 'zh-tw' => '巴貝多']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 112,
                'alpha-2_code' => 'BY',
                'alpha-3_code' => 'BLR',
                'display' => json_encode(['en-us' => 'Belarus', 'zh-tw' => '白俄羅斯']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 56,
                'alpha-2_code' => 'BE',
                'alpha-3_code' => 'BEL',
                'display' => json_encode(['en-us' => 'Belgium', 'zh-tw' => '比利時']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 84,
                'alpha-2_code' => 'BZ',
                'alpha-3_code' => 'BLZ',
                'display' => json_encode(['en-us' => 'Belize', 'zh-tw' => '貝里斯']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 204,
                'alpha-2_code' => 'BJ',
                'alpha-3_code' => 'BEN',
                'display' => json_encode(['en-us' => 'Benin', 'zh-tw' => '貝南']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 60,
                'alpha-2_code' => 'BM',
                'alpha-3_code' => 'BMU',
                'display' => json_encode(['en-us' => 'Bermuda', 'zh-tw' => '百慕達']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 64,
                'alpha-2_code' => 'BT',
                'alpha-3_code' => 'BTN',
                'display' => json_encode(['en-us' => 'Bhutan', 'zh-tw' => '不丹']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 68,
                'alpha-2_code' => 'BO',
                'alpha-3_code' => 'BOL',
                'display' => json_encode(['en-us' => 'Bolivia (Plurinational State of)', 'zh-tw' => '玻利維亞']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 535,
                'alpha-2_code' => 'BQ',
                'alpha-3_code' => 'BES',
                'display' => json_encode(['en-us' => 'Bonaire, Sint Eustatius and Saba', 'zh-tw' => '荷蘭加勒比區']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 70,
                'alpha-2_code' => 'BA',
                'alpha-3_code' => 'BIH',
                'display' => json_encode(['en-us' => 'Bosnia and Herzegovina', 'zh-tw' => '波赫']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 72,
                'alpha-2_code' => 'BW',
                'alpha-3_code' => 'BWA',
                'display' => json_encode(['en-us' => 'Botswana', 'zh-tw' => '波札那']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 74,
                'alpha-2_code' => 'BV',
                'alpha-3_code' => 'BVT',
                'display' => json_encode(['en-us' => 'Bouvet Island', 'zh-tw' => '布韋島']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 76,
                'alpha-2_code' => 'BR',
                'alpha-3_code' => 'BRA',
                'display' => json_encode(['en-us' => 'Brazil', 'zh-tw' => '巴西']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 86,
                'alpha-2_code' => 'IO',
                'alpha-3_code' => 'IOT',
                'display' => json_encode(['en-us' => 'British Indian Ocean Territory', 'zh-tw' => '英屬印度洋領地']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 96,
                'alpha-2_code' => 'BN',
                'alpha-3_code' => 'BRN',
                'display' => json_encode(['en-us' => 'Brunei Darussalam', 'zh-tw' => '汶萊']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 100,
                'alpha-2_code' => 'BG',
                'alpha-3_code' => 'BGR',
                'display' => json_encode(['en-us' => 'Bulgaria', 'zh-tw' => '保加利亞']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 854,
                'alpha-2_code' => 'BF',
                'alpha-3_code' => 'BFA',
                'display' => json_encode(['en-us' => 'Burkina Faso', 'zh-tw' => '布吉納法索']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 108,
                'alpha-2_code' => 'BI',
                'alpha-3_code' => 'BDI',
                'display' => json_encode(['en-us' => 'Burundi', 'zh-tw' => '蒲隆地']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 132,
                'alpha-2_code' => 'CV',
                'alpha-3_code' => 'CPV',
                'display' => json_encode(['en-us' => 'Cabo Verde', 'zh-tw' => '維德角']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 116,
                'alpha-2_code' => 'KH',
                'alpha-3_code' => 'KHM',
                'display' => json_encode(['en-us' => 'Cambodia', 'zh-tw' => '柬埔寨']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 120,
                'alpha-2_code' => 'CM',
                'alpha-3_code' => 'CMR',
                'display' => json_encode(['en-us' => 'Cameroon', 'zh-tw' => '喀麥隆']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 124,
                'alpha-2_code' => 'CA',
                'alpha-3_code' => 'CAN',
                'display' => json_encode(['en-us' => 'Canada', 'zh-tw' => '加拿大']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 136,
                'alpha-2_code' => 'KY',
                'alpha-3_code' => 'CYM',
                'display' => json_encode(['en-us' => 'Cayman Islands', 'zh-tw' => '開曼群島']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 140,
                'alpha-2_code' => 'CF',
                'alpha-3_code' => 'CAF',
                'display' => json_encode(['en-us' => 'Central African Republic', 'zh-tw' => '中非']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 148,
                'alpha-2_code' => 'TD',
                'alpha-3_code' => 'TCD',
                'display' => json_encode(['en-us' => 'Chad', 'zh-tw' => '查德']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 152,
                'alpha-2_code' => 'CL',
                'alpha-3_code' => 'CHL',
                'display' => json_encode(['en-us' => 'Chile', 'zh-tw' => '智利']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 156,
                'alpha-2_code' => 'CN',
                'alpha-3_code' => 'CHN',
                'display' => json_encode(['en-us' => 'China', 'zh-tw' => '中國']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 162,
                'alpha-2_code' => 'CX',
                'alpha-3_code' => 'CXR',
                'display' => json_encode(['en-us' => 'Christmas Island', 'zh-tw' => '聖誕島']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 166,
                'alpha-2_code' => 'CC',
                'alpha-3_code' => 'CCK',
                'display' => json_encode(['en-us' => 'Cocos (Keeling) Islands', 'zh-tw' => '科科斯（基林）群島']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 170,
                'alpha-2_code' => 'CO',
                'alpha-3_code' => 'COL',
                'display' => json_encode(['en-us' => 'Colombia', 'zh-tw' => '哥倫比亞']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 174,
                'alpha-2_code' => 'KM',
                'alpha-3_code' => 'COM',
                'display' => json_encode(['en-us' => 'Comoros', 'zh-tw' => '葛摩']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 178,
                'alpha-2_code' => 'CG',
                'alpha-3_code' => 'COG',
                'display' => json_encode(['en-us' => 'Congo', 'zh-tw' => '剛果共和國']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 180,
                'alpha-2_code' => 'CD',
                'alpha-3_code' => 'COD',
                'display' => json_encode(['en-us' => 'Congo(Democratic Republic of the)', 'zh-tw' => '剛果民主共和國']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 184,
                'alpha-2_code' => 'CK',
                'alpha-3_code' => 'COK',
                'display' => json_encode(['en-us' => 'Cook Islands', 'zh-tw' => '庫克群島']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 188,
                'alpha-2_code' => 'CR',
                'alpha-3_code' => 'CRI',
                'display' => json_encode(['en-us' => 'Costa Rica', 'zh-tw' => '哥斯大黎加']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 384,
                'alpha-2_code' => 'CI',
                'alpha-3_code' => 'CIV',
                'display' => json_encode(['en-us' => 'Côte d\'Ivoire', 'zh-tw' => '象牙海岸']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 191,
                'alpha-2_code' => 'HR',
                'alpha-3_code' => 'HRV',
                'display' => json_encode(['en-us' => 'Croatia', 'zh-tw' => '克羅埃西亞']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 192,
                'alpha-2_code' => 'CU',
                'alpha-3_code' => 'CUB',
                'display' => json_encode(['en-us' => 'Cuba', 'zh-tw' => '古巴']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 531,
                'alpha-2_code' => 'CW',
                'alpha-3_code' => 'CUW',
                'display' => json_encode(['en-us' => 'Curaçao', 'zh-tw' => '古拉索']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 196,
                'alpha-2_code' => 'CY',
                'alpha-3_code' => 'CYP',
                'display' => json_encode(['en-us' => 'Cyprus', 'zh-tw' => '賽普勒斯']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 203,
                'alpha-2_code' => 'CZ',
                'alpha-3_code' => 'CZE',
                'display' => json_encode(['en-us' => 'Czechia', 'zh-tw' => '捷克']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 208,
                'alpha-2_code' => 'DK',
                'alpha-3_code' => 'DNK',
                'display' => json_encode(['en-us' => 'Denmark', 'zh-tw' => '丹麥']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 262,
                'alpha-2_code' => 'DJ',
                'alpha-3_code' => 'DJI',
                'display' => json_encode(['en-us' => 'Djibouti', 'zh-tw' => '吉布地']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 212,
                'alpha-2_code' => 'DM',
                'alpha-3_code' => 'DMA',
                'display' => json_encode(['en-us' => 'Dominica', 'zh-tw' => '多米尼克']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 214,
                'alpha-2_code' => 'DO',
                'alpha-3_code' => 'DOM',
                'display' => json_encode(['en-us' => 'Dominican Republic', 'zh-tw' => '多明尼加']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 218,
                'alpha-2_code' => 'EC',
                'alpha-3_code' => 'ECU',
                'display' => json_encode(['en-us' => 'Ecuador', 'zh-tw' => '厄瓜多']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 818,
                'alpha-2_code' => 'EG',
                'alpha-3_code' => 'EGY',
                'display' => json_encode(['en-us' => 'Egypt', 'zh-tw' => '埃及']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 222,
                'alpha-2_code' => 'SV',
                'alpha-3_code' => 'SLV',
                'display' => json_encode(['en-us' => 'El Salvador', 'zh-tw' => '薩爾瓦多']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 226,
                'alpha-2_code' => 'GQ',
                'alpha-3_code' => 'GNQ',
                'display' => json_encode(['en-us' => 'Equatorial Guinea', 'zh-tw' => '赤道幾內亞']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 232,
                'alpha-2_code' => 'ER',
                'alpha-3_code' => 'ERI',
                'display' => json_encode(['en-us' => 'Eritrea', 'zh-tw' => '厄利垂亞']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 233,
                'alpha-2_code' => 'EE',
                'alpha-3_code' => 'EST',
                'display' => json_encode(['en-us' => 'Estonia', 'zh-tw' => '愛沙尼亞']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 748,
                'alpha-2_code' => 'SZ',
                'alpha-3_code' => 'SWZ',
                'display' => json_encode(['en-us' => 'Eswatini', 'zh-tw' => '史瓦帝尼']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 231,
                'alpha-2_code' => 'ET',
                'alpha-3_code' => 'ETH',
                'display' => json_encode(['en-us' => 'Ethiopia', 'zh-tw' => '衣索比亞']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 238,
                'alpha-2_code' => 'FK',
                'alpha-3_code' => 'FLK',
                'display' => json_encode(['en-us' => 'Falkland Islands (Malvinas)', 'zh-tw' => '福克蘭群島']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 234,
                'alpha-2_code' => 'FO',
                'alpha-3_code' => 'FRO',
                'display' => json_encode(['en-us' => 'Faroe Islands', 'zh-tw' => '法羅群島']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 242,
                'alpha-2_code' => 'FJ',
                'alpha-3_code' => 'FJI',
                'display' => json_encode(['en-us' => 'Fiji', 'zh-tw' => '斐濟']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 246,
                'alpha-2_code' => 'FI',
                'alpha-3_code' => 'FIN',
                'display' => json_encode(['en-us' => 'Finland', 'zh-tw' => '芬蘭']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 250,
                'alpha-2_code' => 'FR',
                'alpha-3_code' => 'FRA',
                'display' => json_encode(['en-us' => 'France', 'zh-tw' => '法國']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 254,
                'alpha-2_code' => 'GF',
                'alpha-3_code' => 'GUF',
                'display' => json_encode(['en-us' => 'French Guiana', 'zh-tw' => '法屬圭亞那']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 258,
                'alpha-2_code' => 'PF',
                'alpha-3_code' => 'PYF',
                'display' => json_encode(['en-us' => 'French Polynesia', 'zh-tw' => '法屬玻里尼西亞']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 260,
                'alpha-2_code' => 'TF',
                'alpha-3_code' => 'ATF',
                'display' => json_encode(['en-us' => 'French Southern Territories', 'zh-tw' => '法屬南部和南極領地']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 266,
                'alpha-2_code' => 'GA',
                'alpha-3_code' => 'GAB',
                'display' => json_encode(['en-us' => 'Gabon', 'zh-tw' => '加彭']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 270,
                'alpha-2_code' => 'GM',
                'alpha-3_code' => 'GMB',
                'display' => json_encode(['en-us' => 'Gambia', 'zh-tw' => '甘比亞']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 268,
                'alpha-2_code' => 'GE',
                'alpha-3_code' => 'GEO',
                'display' => json_encode(['en-us' => 'Georgia', 'zh-tw' => '喬治亞']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 276,
                'alpha-2_code' => 'DE',
                'alpha-3_code' => 'DEU',
                'display' => json_encode(['en-us' => 'Germany', 'zh-tw' => '德國']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 288,
                'alpha-2_code' => 'GH',
                'alpha-3_code' => 'GHA',
                'display' => json_encode(['en-us' => 'Ghana', 'zh-tw' => '加納']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 292,
                'alpha-2_code' => 'GI',
                'alpha-3_code' => 'GIB',
                'display' => json_encode(['en-us' => 'Gibraltar', 'zh-tw' => '直布羅陀']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 300,
                'alpha-2_code' => 'GR',
                'alpha-3_code' => 'GRC',
                'display' => json_encode(['en-us' => 'Greece', 'zh-tw' => '希臘']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 304,
                'alpha-2_code' => 'GL',
                'alpha-3_code' => 'GRL',
                'display' => json_encode(['en-us' => 'Greenland', 'zh-tw' => '格陵蘭']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 308,
                'alpha-2_code' => 'GD',
                'alpha-3_code' => 'GRD',
                'display' => json_encode(['en-us' => 'Grenada', 'zh-tw' => '格瑞那達']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 312,
                'alpha-2_code' => 'GP',
                'alpha-3_code' => 'GLP',
                'display' => json_encode(['en-us' => 'Guadeloupe', 'zh-tw' => '瓜地洛普']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 316,
                'alpha-2_code' => 'GU',
                'alpha-3_code' => 'GUM',
                'display' => json_encode(['en-us' => 'Guam', 'zh-tw' => '關島']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 320,
                'alpha-2_code' => 'GT',
                'alpha-3_code' => 'GTM',
                'display' => json_encode(['en-us' => 'Guatemala', 'zh-tw' => '瓜地馬拉']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 831,
                'alpha-2_code' => 'GG',
                'alpha-3_code' => 'GGY',
                'display' => json_encode(['en-us' => 'Guernsey', 'zh-tw' => '根西']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 324,
                'alpha-2_code' => 'GN',
                'alpha-3_code' => 'GIN',
                'display' => json_encode(['en-us' => 'Guinea', 'zh-tw' => '幾內亞']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 624,
                'alpha-2_code' => 'GW',
                'alpha-3_code' => 'GNB',
                'display' => json_encode(['en-us' => 'Guinea-Bissau', 'zh-tw' => '幾內亞比索']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 328,
                'alpha-2_code' => 'GY',
                'alpha-3_code' => 'GUY',
                'display' => json_encode(['en-us' => 'Guyana', 'zh-tw' => '蓋亞那']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 332,
                'alpha-2_code' => 'HT',
                'alpha-3_code' => 'HTI',
                'display' => json_encode(['en-us' => 'Haiti', 'zh-tw' => '海地']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 334,
                'alpha-2_code' => 'HM',
                'alpha-3_code' => 'HMD',
                'display' => json_encode(['en-us' => 'Heard Island and McDonald Islands', 'zh-tw' => '赫德島和麥克唐納群島']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 336,
                'alpha-2_code' => 'VA',
                'alpha-3_code' => 'VAT',
                'display' => json_encode(['en-us' => 'Holy See', 'zh-tw' => '梵蒂岡']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 340,
                'alpha-2_code' => 'HN',
                'alpha-3_code' => 'HND',
                'display' => json_encode(['en-us' => 'Honduras', 'zh-tw' => '宏都拉斯']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 344,
                'alpha-2_code' => 'HK',
                'alpha-3_code' => 'HKG',
                'display' => json_encode(['en-us' => 'Hong Kong', 'zh-tw' => '香港']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 348,
                'alpha-2_code' => 'HU',
                'alpha-3_code' => 'HUN',
                'display' => json_encode(['en-us' => 'Hungary', 'zh-tw' => '匈牙利']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 352,
                'alpha-2_code' => 'IS',
                'alpha-3_code' => 'ISL',
                'display' => json_encode(['en-us' => 'Iceland', 'zh-tw' => '冰島']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 356,
                'alpha-2_code' => 'IN',
                'alpha-3_code' => 'IND',
                'display' => json_encode(['en-us' => 'India', 'zh-tw' => '印度']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 360,
                'alpha-2_code' => 'ID',
                'alpha-3_code' => 'IDN',
                'display' => json_encode(['en-us' => 'Indonesia', 'zh-tw' => '印尼']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 364,
                'alpha-2_code' => 'IR',
                'alpha-3_code' => 'IRN',
                'display' => json_encode(['en-us' => 'Iran (Islamic Republic of)', 'zh-tw' => '伊朗']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 368,
                'alpha-2_code' => 'IQ',
                'alpha-3_code' => 'IRQ',
                'display' => json_encode(['en-us' => 'Iraq', 'zh-tw' => '伊拉克']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 372,
                'alpha-2_code' => 'IE',
                'alpha-3_code' => 'IRL',
                'display' => json_encode(['en-us' => 'Ireland', 'zh-tw' => '愛爾蘭']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 833,
                'alpha-2_code' => 'IM',
                'alpha-3_code' => 'IMN',
                'display' => json_encode(['en-us' => 'Isle of Man', 'zh-tw' => '曼島']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 376,
                'alpha-2_code' => 'IL',
                'alpha-3_code' => 'ISR',
                'display' => json_encode(['en-us' => 'Israel', 'zh-tw' => '以色列']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 380,
                'alpha-2_code' => 'IT',
                'alpha-3_code' => 'ITA',
                'display' => json_encode(['en-us' => 'Italy', 'zh-tw' => '義大利']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 388,
                'alpha-2_code' => 'JM',
                'alpha-3_code' => 'JAM',
                'display' => json_encode(['en-us' => 'Jamaica', 'zh-tw' => '牙買加']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 392,
                'alpha-2_code' => 'JP',
                'alpha-3_code' => 'JPN',
                'display' => json_encode(['en-us' => 'Japan', 'zh-tw' => '日本']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 832,
                'alpha-2_code' => 'JE',
                'alpha-3_code' => 'JEY',
                'display' => json_encode(['en-us' => 'Jersey', 'zh-tw' => '澤西']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 400,
                'alpha-2_code' => 'JO',
                'alpha-3_code' => 'JOR',
                'display' => json_encode(['en-us' => 'Jordan', 'zh-tw' => '約旦']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 398,
                'alpha-2_code' => 'KZ',
                'alpha-3_code' => 'KAZ',
                'display' => json_encode(['en-us' => 'Kazakhstan', 'zh-tw' => '哈薩克']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 404,
                'alpha-2_code' => 'KE',
                'alpha-3_code' => 'KEN',
                'display' => json_encode(['en-us' => 'Kenya', 'zh-tw' => '肯亞']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 296,
                'alpha-2_code' => 'KI',
                'alpha-3_code' => 'KIR',
                'display' => json_encode(['en-us' => 'Kiribati', 'zh-tw' => '吉里巴斯']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 408,
                'alpha-2_code' => 'KP',
                'alpha-3_code' => 'PRK',
                'display' => json_encode(['en-us' => 'Korea(Democratic People\'s Republic of)', 'zh-tw' => '北韓']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 410,
                'alpha-2_code' => 'KR',
                'alpha-3_code' => 'KOR',
                'display' => json_encode(['en-us' => 'Korea (Republic of)', 'zh-tw' => '韓國']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 414,
                'alpha-2_code' => 'KW',
                'alpha-3_code' => 'KWT',
                'display' => json_encode(['en-us' => 'Kuwait', 'zh-tw' => '科威特']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 417,
                'alpha-2_code' => 'KG',
                'alpha-3_code' => 'KGZ',
                'display' => json_encode(['en-us' => 'Kyrgyzstan', 'zh-tw' => '吉爾吉斯']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 418,
                'alpha-2_code' => 'LA',
                'alpha-3_code' => 'LAO',
                'display' => json_encode(['en-us' => 'Lao People\'s Democratic Republic', 'zh-tw' => '寮國']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 428,
                'alpha-2_code' => 'LV',
                'alpha-3_code' => 'LVA',
                'display' => json_encode(['en-us' => 'Latvia', 'zh-tw' => '拉脫維亞']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 422,
                'alpha-2_code' => 'LB',
                'alpha-3_code' => 'LBN',
                'display' => json_encode(['en-us' => 'Lebanon', 'zh-tw' => '黎巴嫩']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 426,
                'alpha-2_code' => 'LS',
                'alpha-3_code' => 'LSO',
                'display' => json_encode(['en-us' => 'Lesotho', 'zh-tw' => '賴索托']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 430,
                'alpha-2_code' => 'LR',
                'alpha-3_code' => 'LBR',
                'display' => json_encode(['en-us' => 'Liberia', 'zh-tw' => '賴比瑞亞']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 434,
                'alpha-2_code' => 'LY',
                'alpha-3_code' => 'LBY',
                'display' => json_encode(['en-us' => 'Libya', 'zh-tw' => '利比亞']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 438,
                'alpha-2_code' => 'LI',
                'alpha-3_code' => 'LIE',
                'display' => json_encode(['en-us' => 'Liechtenstein', 'zh-tw' => '列支敦斯登']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 440,
                'alpha-2_code' => 'LT',
                'alpha-3_code' => 'LTU',
                'display' => json_encode(['en-us' => 'Lithuania', 'zh-tw' => '立陶宛']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 442,
                'alpha-2_code' => 'LU',
                'alpha-3_code' => 'LUX',
                'display' => json_encode(['en-us' => 'Luxembourg', 'zh-tw' => '盧森堡']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 446,
                'alpha-2_code' => 'MO',
                'alpha-3_code' => 'MAC',
                'display' => json_encode(['en-us' => 'Macao', 'zh-tw' => '澳門']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 450,
                'alpha-2_code' => 'MG',
                'alpha-3_code' => 'MDG',
                'display' => json_encode(['en-us' => 'Madagascar', 'zh-tw' => '馬達加斯加']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 454,
                'alpha-2_code' => 'MW',
                'alpha-3_code' => 'MWI',
                'display' => json_encode(['en-us' => 'Malawi', 'zh-tw' => '馬拉威']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 458,
                'alpha-2_code' => 'MY',
                'alpha-3_code' => 'MYS',
                'display' => json_encode(['en-us' => 'Malaysia', 'zh-tw' => '馬來西亞']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 462,
                'alpha-2_code' => 'MV',
                'alpha-3_code' => 'MDV',
                'display' => json_encode(['en-us' => 'Maldives', 'zh-tw' => '馬爾地夫']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 466,
                'alpha-2_code' => 'ML',
                'alpha-3_code' => 'MLI',
                'display' => json_encode(['en-us' => 'Mali', 'zh-tw' => '馬利']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 470,
                'alpha-2_code' => 'MT',
                'alpha-3_code' => 'MLT',
                'display' => json_encode(['en-us' => 'Malta', 'zh-tw' => '馬爾他']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 584,
                'alpha-2_code' => 'MH',
                'alpha-3_code' => 'MHL',
                'display' => json_encode(['en-us' => 'Marshall Islands', 'zh-tw' => '馬紹爾群島']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 474,
                'alpha-2_code' => 'MQ',
                'alpha-3_code' => 'MTQ',
                'display' => json_encode(['en-us' => 'Martinique', 'zh-tw' => '馬丁尼克']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 478,
                'alpha-2_code' => 'MR',
                'alpha-3_code' => 'MRT',
                'display' => json_encode(['en-us' => 'Mauritania', 'zh-tw' => '茅利塔尼亞']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 480,
                'alpha-2_code' => 'MU',
                'alpha-3_code' => 'MUS',
                'display' => json_encode(['en-us' => 'Mauritius', 'zh-tw' => '模里西斯']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 175,
                'alpha-2_code' => 'YT',
                'alpha-3_code' => 'MYT',
                'display' => json_encode(['en-us' => 'Mayotte', 'zh-tw' => '馬約特']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 484,
                'alpha-2_code' => 'MX',
                'alpha-3_code' => 'MEX',
                'display' => json_encode(['en-us' => 'Mexico', 'zh-tw' => '墨西哥']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 583,
                'alpha-2_code' => 'FM',
                'alpha-3_code' => 'FSM',
                'display' => json_encode(['en-us' => 'Micronesia (Federated States of)', 'zh-tw' => '密克羅尼西亞聯邦']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 498,
                'alpha-2_code' => 'MD',
                'alpha-3_code' => 'MDA',
                'display' => json_encode(['en-us' => 'Moldova (Republic of)', 'zh-tw' => '摩爾多瓦']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 492,
                'alpha-2_code' => 'MC',
                'alpha-3_code' => 'MCO',
                'display' => json_encode(['en-us' => 'Monaco', 'zh-tw' => '摩納哥']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 496,
                'alpha-2_code' => 'MN',
                'alpha-3_code' => 'MNG',
                'display' => json_encode(['en-us' => 'Mongolia', 'zh-tw' => '蒙古國']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 499,
                'alpha-2_code' => 'ME',
                'alpha-3_code' => 'MNE',
                'display' => json_encode(['en-us' => 'Montenegro', 'zh-tw' => '蒙特內哥羅']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 500,
                'alpha-2_code' => 'MS',
                'alpha-3_code' => 'MSR',
                'display' => json_encode(['en-us' => 'Montserrat', 'zh-tw' => '蒙特塞拉特']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 504,
                'alpha-2_code' => 'MA',
                'alpha-3_code' => 'MAR',
                'display' => json_encode(['en-us' => 'Morocco', 'zh-tw' => '摩洛哥']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 508,
                'alpha-2_code' => 'MZ',
                'alpha-3_code' => 'MOZ',
                'display' => json_encode(['en-us' => 'Mozambique', 'zh-tw' => '莫三比克']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 104,
                'alpha-2_code' => 'MM',
                'alpha-3_code' => 'MMR',
                'display' => json_encode(['en-us' => 'Myanmar', 'zh-tw' => '緬甸']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 516,
                'alpha-2_code' => 'NA',
                'alpha-3_code' => 'NAM',
                'display' => json_encode(['en-us' => 'Namibia', 'zh-tw' => '納米比亞']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 520,
                'alpha-2_code' => 'NR',
                'alpha-3_code' => 'NRU',
                'display' => json_encode(['en-us' => 'Nauru', 'zh-tw' => '諾魯']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 524,
                'alpha-2_code' => 'NP',
                'alpha-3_code' => 'NPL',
                'display' => json_encode(['en-us' => 'Nepal', 'zh-tw' => '尼泊爾']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 528,
                'alpha-2_code' => 'NL',
                'alpha-3_code' => 'NLD',
                'display' => json_encode(['en-us' => 'Netherlands', 'zh-tw' => '荷蘭']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 540,
                'alpha-2_code' => 'NC',
                'alpha-3_code' => 'NCL',
                'display' => json_encode(['en-us' => 'New Caledonia', 'zh-tw' => '新喀里多尼亞']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 554,
                'alpha-2_code' => 'NZ',
                'alpha-3_code' => 'NZL',
                'display' => json_encode(['en-us' => 'New Zealand', 'zh-tw' => '紐西蘭']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 558,
                'alpha-2_code' => 'NI',
                'alpha-3_code' => 'NIC',
                'display' => json_encode(['en-us' => 'Nicaragua', 'zh-tw' => '尼加拉瓜']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 562,
                'alpha-2_code' => 'NE',
                'alpha-3_code' => 'NER',
                'display' => json_encode(['en-us' => 'Niger', 'zh-tw' => '尼日']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 566,
                'alpha-2_code' => 'NG',
                'alpha-3_code' => 'NGA',
                'display' => json_encode(['en-us' => 'Nigeria', 'zh-tw' => '奈及利亞']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 570,
                'alpha-2_code' => 'NU',
                'alpha-3_code' => 'NIU',
                'display' => json_encode(['en-us' => 'Niue', 'zh-tw' => '紐埃']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 574,
                'alpha-2_code' => 'NF',
                'alpha-3_code' => 'NFK',
                'display' => json_encode(['en-us' => 'Norfolk Island', 'zh-tw' => '諾福克島']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 807,
                'alpha-2_code' => 'MK',
                'alpha-3_code' => 'MKD',
                'display' => json_encode(['en-us' => 'North Macedonia', 'zh-tw' => '北馬其頓']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 580,
                'alpha-2_code' => 'MP',
                'alpha-3_code' => 'MNP',
                'display' => json_encode(['en-us' => 'Northern Mariana Islands', 'zh-tw' => '北馬利安納群島']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 578,
                'alpha-2_code' => 'NO',
                'alpha-3_code' => 'NOR',
                'display' => json_encode(['en-us' => 'Norway', 'zh-tw' => '挪威']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 512,
                'alpha-2_code' => 'OM',
                'alpha-3_code' => 'OMN',
                'display' => json_encode(['en-us' => 'Oman', 'zh-tw' => '阿曼']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 586,
                'alpha-2_code' => 'PK',
                'alpha-3_code' => 'PAK',
                'display' => json_encode(['en-us' => 'Pakistan', 'zh-tw' => '巴基斯坦']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 585,
                'alpha-2_code' => 'PW',
                'alpha-3_code' => 'PLW',
                'display' => json_encode(['en-us' => 'Palau', 'zh-tw' => '帛琉']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 275,
                'alpha-2_code' => 'PS',
                'alpha-3_code' => 'PSE',
                'display' => json_encode(['en-us' => 'Palestine, State of', 'zh-tw' => '巴勒斯坦']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 591,
                'alpha-2_code' => 'PA',
                'alpha-3_code' => 'PAN',
                'display' => json_encode(['en-us' => 'Panama', 'zh-tw' => '巴拿馬']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 598,
                'alpha-2_code' => 'PG',
                'alpha-3_code' => 'PNG',
                'display' => json_encode(['en-us' => 'Papua New Guinea', 'zh-tw' => '巴布亞紐幾內亞']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 600,
                'alpha-2_code' => 'PY',
                'alpha-3_code' => 'PRY',
                'display' => json_encode(['en-us' => 'Paraguay', 'zh-tw' => '巴拉圭']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 604,
                'alpha-2_code' => 'PE',
                'alpha-3_code' => 'PER',
                'display' => json_encode(['en-us' => 'Peru', 'zh-tw' => '秘魯']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 608,
                'alpha-2_code' => 'PH',
                'alpha-3_code' => 'PHL',
                'display' => json_encode(['en-us' => 'Philippines', 'zh-tw' => '菲律賓']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 612,
                'alpha-2_code' => 'PN',
                'alpha-3_code' => 'PCN',
                'display' => json_encode(['en-us' => 'Pitcairn', 'zh-tw' => '皮特肯群島']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 616,
                'alpha-2_code' => 'PL',
                'alpha-3_code' => 'POL',
                'display' => json_encode(['en-us' => 'Poland', 'zh-tw' => '波蘭']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 620,
                'alpha-2_code' => 'PT',
                'alpha-3_code' => 'PRT',
                'display' => json_encode(['en-us' => 'Portugal', 'zh-tw' => '葡萄牙']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 630,
                'alpha-2_code' => 'PR',
                'alpha-3_code' => 'PRI',
                'display' => json_encode(['en-us' => 'Puerto Rico', 'zh-tw' => '波多黎各']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 634,
                'alpha-2_code' => 'QA',
                'alpha-3_code' => 'QAT',
                'display' => json_encode(['en-us' => 'Qatar', 'zh-tw' => '卡達']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 638,
                'alpha-2_code' => 'RE',
                'alpha-3_code' => 'REU',
                'display' => json_encode(['en-us' => 'Réunion', 'zh-tw' => '留尼旺']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 642,
                'alpha-2_code' => 'RO',
                'alpha-3_code' => 'ROU',
                'display' => json_encode(['en-us' => 'Romania', 'zh-tw' => '羅馬尼亞']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 643,
                'alpha-2_code' => 'RU',
                'alpha-3_code' => 'RUS',
                'display' => json_encode(['en-us' => 'Russian Federation', 'zh-tw' => '俄羅斯']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 646,
                'alpha-2_code' => 'RW',
                'alpha-3_code' => 'RWA',
                'display' => json_encode(['en-us' => 'Rwanda', 'zh-tw' => '盧安達']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 652,
                'alpha-2_code' => 'BL',
                'alpha-3_code' => 'BLM',
                'display' => json_encode(['en-us' => 'Saint Barthélemy', 'zh-tw' => '聖巴瑟米']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 654,
                'alpha-2_code' => 'SH',
                'alpha-3_code' => 'SHN',
                'display' => json_encode(['en-us' => 'Saint Helena, Ascension and Tristan da Cunha', 'zh-tw' => '聖赫倫那、阿森松和特里斯坦-達庫尼亞']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 659,
                'alpha-2_code' => 'KN',
                'alpha-3_code' => 'KNA',
                'display' => json_encode(['en-us' => 'Saint Kitts and Nevis', 'zh-tw' => '聖克里斯多福及尼維斯']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 662,
                'alpha-2_code' => 'LC',
                'alpha-3_code' => 'LCA',
                'display' => json_encode(['en-us' => 'Saint Lucia', 'zh-tw' => '聖露西亞']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 663,
                'alpha-2_code' => 'MF',
                'alpha-3_code' => 'MAF',
                'display' => json_encode(['en-us' => 'Saint Martin(French part)', 'zh-tw' => '法屬聖馬丁']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 666,
                'alpha-2_code' => 'PM',
                'alpha-3_code' => 'SPM',
                'display' => json_encode(['en-us' => 'Saint Pierre and Miquelon', 'zh-tw' => '聖皮埃與密克隆群島']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 670,
                'alpha-2_code' => 'VC',
                'alpha-3_code' => 'VCT',
                'display' => json_encode(['en-us' => 'Saint Vincent and the Grenadines', 'zh-tw' => '聖文森及格瑞那丁']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 882,
                'alpha-2_code' => 'WS',
                'alpha-3_code' => 'WSM',
                'display' => json_encode(['en-us' => 'Samoa', 'zh-tw' => '薩摩亞']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 674,
                'alpha-2_code' => 'SM',
                'alpha-3_code' => 'SMR',
                'display' => json_encode(['en-us' => 'San Marino', 'zh-tw' => '聖馬利諾']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 678,
                'alpha-2_code' => 'ST',
                'alpha-3_code' => 'STP',
                'display' => json_encode(['en-us' => 'Sao Tome and Principe', 'zh-tw' => '聖多美普林西比']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 682,
                'alpha-2_code' => 'SA',
                'alpha-3_code' => 'SAU',
                'display' => json_encode(['en-us' => 'Saudi Arabia', 'zh-tw' => '沙烏地阿拉伯']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 686,
                'alpha-2_code' => 'SN',
                'alpha-3_code' => 'SEN',
                'display' => json_encode(['en-us' => 'Senegal', 'zh-tw' => '塞內加爾']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 688,
                'alpha-2_code' => 'RS',
                'alpha-3_code' => 'SRB',
                'display' => json_encode(['en-us' => 'Serbia', 'zh-tw' => '塞爾維亞']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 690,
                'alpha-2_code' => 'SC',
                'alpha-3_code' => 'SYC',
                'display' => json_encode(['en-us' => 'Seychelles', 'zh-tw' => '塞席爾']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 694,
                'alpha-2_code' => 'SL',
                'alpha-3_code' => 'SLE',
                'display' => json_encode(['en-us' => 'Sierra Leone', 'zh-tw' => '獅子山']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 702,
                'alpha-2_code' => 'SG',
                'alpha-3_code' => 'SGP',
                'display' => json_encode(['en-us' => 'Singapore', 'zh-tw' => '新加坡']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 534,
                'alpha-2_code' => 'SX',
                'alpha-3_code' => 'SXM',
                'display' => json_encode(['en-us' => 'Sint Maarten(Dutch part)', 'zh-tw' => '荷屬聖馬丁']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 703,
                'alpha-2_code' => 'SK',
                'alpha-3_code' => 'SVK',
                'display' => json_encode(['en-us' => 'Slovakia', 'zh-tw' => '斯洛伐克']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 705,
                'alpha-2_code' => 'SI',
                'alpha-3_code' => 'SVN',
                'display' => json_encode(['en-us' => 'Slovenia', 'zh-tw' => '斯洛維尼亞']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 90,
                'alpha-2_code' => 'SB',
                'alpha-3_code' => 'SLB',
                'display' => json_encode(['en-us' => 'Solomon Islands', 'zh-tw' => '索羅門群島']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 706,
                'alpha-2_code' => 'SO',
                'alpha-3_code' => 'SOM',
                'display' => json_encode(['en-us' => 'Somalia', 'zh-tw' => '索馬利亞']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 710,
                'alpha-2_code' => 'ZA',
                'alpha-3_code' => 'ZAF',
                'display' => json_encode(['en-us' => 'South Africa', 'zh-tw' => '南非']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 239,
                'alpha-2_code' => 'GS',
                'alpha-3_code' => 'SGS',
                'display' => json_encode(['en-us' => 'South Georgia and the South Sandwich Islands', 'zh-tw' => '南喬治亞和南桑威奇群島']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 728,
                'alpha-2_code' => 'SS',
                'alpha-3_code' => 'SSD',
                'display' => json_encode(['en-us' => 'South Sudan', 'zh-tw' => '南蘇丹']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 724,
                'alpha-2_code' => 'ES',
                'alpha-3_code' => 'ESP',
                'display' => json_encode(['en-us' => 'Spain', 'zh-tw' => '西班牙']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 144,
                'alpha-2_code' => 'LK',
                'alpha-3_code' => 'LKA',
                'display' => json_encode(['en-us' => 'Sri Lanka', 'zh-tw' => '斯里蘭卡']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 729,
                'alpha-2_code' => 'SD',
                'alpha-3_code' => 'SDN',
                'display' => json_encode(['en-us' => 'Sudan', 'zh-tw' => '蘇丹']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 740,
                'alpha-2_code' => 'SR',
                'alpha-3_code' => 'SUR',
                'display' => json_encode(['en-us' => 'Suriname', 'zh-tw' => '蘇利南']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 744,
                'alpha-2_code' => 'SJ',
                'alpha-3_code' => 'SJM',
                'display' => json_encode(['en-us' => 'Svalbard and Jan Mayen', 'zh-tw' => '斯瓦爾巴和揚馬延']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 752,
                'alpha-2_code' => 'SE',
                'alpha-3_code' => 'SWE',
                'display' => json_encode(['en-us' => 'Sweden', 'zh-tw' => '瑞典']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 756,
                'alpha-2_code' => 'CH',
                'alpha-3_code' => 'CHE',
                'display' => json_encode(['en-us' => 'Switzerland', 'zh-tw' => '瑞士']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 760,
                'alpha-2_code' => 'SY',
                'alpha-3_code' => 'SYR',
                'display' => json_encode(['en-us' => 'Syrian Arab Republic', 'zh-tw' => '敘利亞']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 158,
                'alpha-2_code' => 'TW',
                'alpha-3_code' => 'TWN',
                'display' => json_encode(['en-us' => 'Taiwan', 'zh-tw' => '臺灣']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 762,
                'alpha-2_code' => 'TJ',
                'alpha-3_code' => 'TJK',
                'display' => json_encode(['en-us' => 'Tajikistan', 'zh-tw' => '塔吉克']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 834,
                'alpha-2_code' => 'TZ',
                'alpha-3_code' => 'TZA',
                'display' => json_encode(['en-us' => 'Tanzania, United Republic of', 'zh-tw' => '坦尚尼亞']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 764,
                'alpha-2_code' => 'TH',
                'alpha-3_code' => 'THA',
                'display' => json_encode(['en-us' => 'Thailand', 'zh-tw' => '泰國']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 626,
                'alpha-2_code' => 'TL',
                'alpha-3_code' => 'TLS',
                'display' => json_encode(['en-us' => 'Timor - Leste', 'zh-tw' => '東帝汶']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 768,
                'alpha-2_code' => 'TG',
                'alpha-3_code' => 'TGO',
                'display' => json_encode(['en-us' => 'Togo', 'zh-tw' => '多哥']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 772,
                'alpha-2_code' => 'TK',
                'alpha-3_code' => 'TKL',
                'display' => json_encode(['en-us' => 'Tokelau', 'zh-tw' => '托克勞']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 776,
                'alpha-2_code' => 'TO',
                'alpha-3_code' => 'TON',
                'display' => json_encode(['en-us' => 'Tonga', 'zh-tw' => '東加']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 780,
                'alpha-2_code' => 'TT',
                'alpha-3_code' => 'TTO',
                'display' => json_encode(['en-us' => 'Trinidad and Tobago', 'zh-tw' => '千里達及托巴哥']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 788,
                'alpha-2_code' => 'TN',
                'alpha-3_code' => 'TUN',
                'display' => json_encode(['en-us' => 'Tunisia', 'zh-tw' => '突尼西亞']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 792,
                'alpha-2_code' => 'TR',
                'alpha-3_code' => 'TUR',
                'display' => json_encode(['en-us' => 'Turkey', 'zh-tw' => '土耳其']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 795,
                'alpha-2_code' => 'TM',
                'alpha-3_code' => 'TKM',
                'display' => json_encode(['en-us' => 'Turkmenistan', 'zh-tw' => '土庫曼']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 796,
                'alpha-2_code' => 'TC',
                'alpha-3_code' => 'TCA',
                'display' => json_encode(['en-us' => 'Turks and Caicos Islands', 'zh-tw' => '特克斯與凱科斯群島']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 798,
                'alpha-2_code' => 'TV',
                'alpha-3_code' => 'TUV',
                'display' => json_encode(['en-us' => 'Tuvalu', 'zh-tw' => '吐瓦魯']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 800,
                'alpha-2_code' => 'UG',
                'alpha-3_code' => 'UGA',
                'display' => json_encode(['en-us' => 'Uganda', 'zh-tw' => '烏干達']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 804,
                'alpha-2_code' => 'UA',
                'alpha-3_code' => 'UKR',
                'display' => json_encode(['en-us' => 'Ukraine', 'zh-tw' => '烏克蘭']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 784,
                'alpha-2_code' => 'AE',
                'alpha-3_code' => 'ARE',
                'display' => json_encode(['en-us' => 'United Arab Emirates', 'zh-tw' => '阿聯']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 826,
                'alpha-2_code' => 'GB',
                'alpha-3_code' => 'GBR',
                'display' => json_encode(['en-us' => 'United Kingdom of Great Britain and Northern Ireland', 'zh-tw' => '英國']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 840,
                'alpha-2_code' => 'US',
                'alpha-3_code' => 'USA',
                'display' => json_encode(['en-us' => 'United States of America', 'zh-tw' => '美國']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 581,
                'alpha-2_code' => 'UM',
                'alpha-3_code' => 'UMI',
                'display' => json_encode(['en-us' => 'United States Minor Outlying Islands', 'zh-tw' => '美國本土外小島嶼']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 858,
                'alpha-2_code' => 'UY',
                'alpha-3_code' => 'URY',
                'display' => json_encode(['en-us' => 'Uruguay', 'zh-tw' => '烏拉圭']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 860,
                'alpha-2_code' => 'UZ',
                'alpha-3_code' => 'UZB',
                'display' => json_encode(['en-us' => 'Uzbekistan', 'zh-tw' => '烏茲別克']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 548,
                'alpha-2_code' => 'VU',
                'alpha-3_code' => 'VUT',
                'display' => json_encode(['en-us' => 'Vanuatu', 'zh-tw' => '萬那杜']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 862,
                'alpha-2_code' => 'VE',
                'alpha-3_code' => 'VEN',
                'display' => json_encode(['en-us' => 'Venezuela(Bolivarian Republic of)', 'zh-tw' => '委內瑞拉']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 704,
                'alpha-2_code' => 'VN',
                'alpha-3_code' => 'VNM',
                'display' => json_encode(['en-us' => 'Viet Nam', 'zh-tw' => '越南']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 92,
                'alpha-2_code' => 'VG',
                'alpha-3_code' => 'VGB',
                'display' => json_encode(['en-us' => 'Virgin Islands(British)', 'zh-tw' => '英屬維京群島']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 850,
                'alpha-2_code' => 'VI',
                'alpha-3_code' => 'VIR',
                'display' => json_encode(['en-us' => 'Virgin Islands(U . S .)', 'zh-tw' => '美屬維京群島']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 876,
                'alpha-2_code' => 'WF',
                'alpha-3_code' => 'WLF',
                'display' => json_encode(['en-us' => 'Wallis and Futuna', 'zh-tw' => '瓦利斯和富圖那']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 732,
                'alpha-2_code' => 'EH',
                'alpha-3_code' => 'ESH',
                'display' => json_encode(['en-us' => 'Western Sahara', 'zh-tw' => '撒拉威阿拉伯民主共和國']),
                'is_independent' => 0,
            ],
            [
                'numeric_code' => 887,
                'alpha-2_code' => 'YE',
                'alpha-3_code' => 'YEM',
                'display' => json_encode(['en-us' => 'Yemen', 'zh-tw' => '葉門']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 894,
                'alpha-2_code' => 'ZM',
                'alpha-3_code' => 'ZMB',
                'display' => json_encode(['en-us' => 'Zambia', 'zh-tw' => '尚比亞']),
                'is_independent' => 1,
            ],
            [
                'numeric_code' => 716,
                'alpha-2_code' => 'ZW',
                'alpha-3_code' => 'ZWE',
                'display' => json_encode(['en-us' => 'Zimbabwe', 'zh-tw' => '辛巴威']),
                'is_independent' => 1,
            ],
        ]);
    }
}
