services:
  # 開發核心：直接跑 Artisan Serve
  app:
    image: php:8.2-cli-alpine # 開發用 cli 版本即可，更輕量
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: taicol-nametool-dev-app
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    ports:
      - "8000:8000" # 將容器的 8000 對應到你電腦的 8000
    command: php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      - redis
    networks:
      - taicol-db 
      - internal
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:alpine
    container_name: taicol-nametool-dev-redis
    ports:
      - "6379:6379"
    networks:
      - internal
  worker:
      image: php:8.2-cli-alpine
      build:
        context: ./docker/php
        dockerfile: Dockerfile
      container_name: taicol-nametool-dev-worker
      volumes:
        - .:/var/www/html
      working_dir: /var/www/html
      command: php artisan queue:work --tries=1 --max-jobs=50 --max-time=3600 --memory=512
      restart: unless-stopped
      depends_on:
        - redis
      networks:
        - internal
networks:
  # 定義外部網路連結
  taicol-db:
    external: true
    name: taicol-web-2022-1_default
  internal: