networks:
  gateway:
    external: true
  traefik-nametool:
    external: true


services:
  nametool_app:
    build: 
      context: .
      dockerfile: docker/php/Dockerfile-stag
    container_name: taicol-nametool-stag-app
    restart: always
    volumes:
      - .:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - redis
    networks:
      - gateway
      - traefik-nametool
    deploy:
      resources:
        limits:
          memory: 400M  # 給予適中的上限
        reservations:
          memory: 128M  # 保證它最少有 128M 可用

  nametool_web:
    image: nginx:alpine
    container_name: taicol-nametool-stag-web
    restart: always
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    networks:
      - gateway
      - traefik-nametool
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.taicol-web.rule=Host(`staging.taicol.tw`)"
      - "traefik.http.routers.taicol-web.entrypoints=websecure"
      - "traefik.http.routers.taicol-web.tls.certresolver=myresolver"
    deploy:
      resources:
        limits:
          memory: 64M

  redis:
    image: redis:alpine
    container_name: taicol-nametool-stag-redis
    networks:
      - gateway
      - traefik-nametool
    # 當記憶體滿了，自動刪除舊的快取（LRU 演算法）
    command: redis-server --maxmemory 100mb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          memory: 128M

  worker:
    build: 
      context: .
      dockerfile: docker/php/Dockerfile-stag
    container_name: taicol-nametool-stag-worker
    command: php /var/www/html/artisan queue:work
    volumes:
      - .:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - gateway
      - traefik-nametool
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          memory: 200M