export default [
    {
        'type': '地位標註(status)',
        'name': 'nomen protectum',
        'abbreviation': 'nom. prot.',
        'definition': '受保護名',
        'status': 'accepted',
        'group': ['animal'],
    },
    {
        'type': '地位標註(status)',
        'name': 'nomen conservandum',
        'abbreviation': 'nom. cons.',
        'definition': '保留名',
        'status': 'accepted',
        'group': ['plant', 'bacteria'],
    },
    {
        'type': '處理標註(treatment)',
        'name': 'classis nova',
        'abbreviation': 'class. nov.',
        'definition': '新綱',
        'status': 'accepted',
        'group': ['animal', 'plant', 'bacteria'],
    },
    {
        'type': '處理標註(treatment)',
        'name': 'combinatio nova',
        'abbreviation': 'comb. nov.',
        'definition': '新組合',
        'status': 'accepted',
        'group': ['animal', 'plant', 'bacteria'],
    },
    {
        'type': '處理標註(treatment)',
        'name': 'combination revived',
        'abbreviation': 'comb. rev.',
        'definition': '組合恢復',
        'status': 'accepted',
        'group': ['animal', 'plant', 'bacteria'],
    },
    {
        'type': '處理標註(treatment)',
        'name': 'familia nova',
        'abbreviation': 'fam. nov.',
        'definition': '新科',
        'status': 'accepted',
        'group': ['animal', 'plant', 'bacteria'],
    },
    {
        'type': '處理標註(treatment)',
        'name': 'genus novum',
        'abbreviation': 'gen. nov.',
        'definition': '新屬',
        'status': 'accepted',
        'group': ['animal', 'plant', 'bacteria'],
    },
    {
        'type': '處理標註(treatment)',
        'name': 'nomem novum',
        'abbreviation': 'nom. nov.',
        'definition': '新名',
        'status': 'accepted',
        'group': ['animal', 'plant', 'bacteria'],
    },
    {
        'type': '處理標註(treatment)',
        'name': 'nomen revictum',
        'abbreviation': 'nom. rev.',
        'definition': '恢復名',
        'status': 'accepted',
        'group': ['animal', 'plant', 'bacteria'],
    },
    {
        'type': '處理標註(treatment)',
        'name': 'ordo novus',
        'abbreviation': 'ord. nov.',
        'definition': '新目',
        'status': 'accepted',
        'group': ['animal', 'plant', 'bacteria'],
    },
    {
        'type': '處理標註(treatment)',
        'name': 'species novum',
        'abbreviation': 'sp. nov.',
        'definition': '新種',
        'status': 'accepted',
        'group': ['animal', 'plant', 'bacteria'],
    },
    {
        'type': '處理標註(treatment)',
        'name': 'subspecies novum',
        'abbreviation': 'ssp. nov.',
        'definition': '新亞種',
        'status': 'accepted',
        'group': ['animal', 'plant', 'bacteria'],
    },
    {
        'type': '處理標註(treatment)',
        'name': 'status novus',
        'abbreviation': 'stat. nov.',
        'definition': '新地位',
        'status': 'accepted',
        'group': ['animal', 'plant', 'bacteria'],
    },
    {
        'type': '處理標註(treatment)',
        'name': 'status revived',
        'abbreviation': 'stat. rev.',
        'definition': '地位恢復',
        'status': 'accepted',
        'group': ['animal', 'plant', 'bacteria'],
    },
    {
        'type': 'description',
        'name': 'nomen alternativum',
        'abbreviation': 'nom. alt.',
        'definition': '替換名。一作者同時對同一分類群依據相同模式發表可做替換的兩個或多個名稱，1953年以前發表則皆為合法，之後則皆不合法。',
        'status': 'accepted',
        'group': ['plant'],
    },
    {
        'type': 'description',
        'name': 'nomen approbatum',
        'abbreviation': 'nom. approb.',
        'definition': '批准名。列入 Approved List of Bacterial Names的學名。',
        'status': 'accepted',
        'group': ['bacteria'],
    },
    {
        'type': 'description',
        'name': 'nomen sanctionatum',
        'abbreviation': 'nom. sanct.',
        'definition': '公認名。真菌類所使用，用以標註對先出同名或競爭而取得保留的學名。',
        'status': 'accepted',
        'group': ['plant'],
    },
    {
        'type': 'description',
        'name': 'pro hybrida',
        'abbreviation': 'pro. hybr.',
        'definition': '名稱發表時以雜交種發表。',
        'status': 'accepted',
        'group': ['animal', 'plant', 'bacteria'],
    },
    {
        'type': 'description',
        'name': 'pro specie',
        'abbreviation': 'pro. sp.',
        'definition': '名稱發表時以種發表。',
        'status': 'accepted',
        'group': ['animal', 'plant', 'bacteria'],
    },
    {
        'type': 'description',
        'name': 'pro synonymo',
        'abbreviation': 'pro. syn.',
        'definition': '名稱發表時以同物異名發表。As synonym.',
        'status': 'accepted',
        'group': ['animal', 'plant', 'bacteria'],
    },
    {
        'type': '拼法標註(orthographic)',
        'name': 'orthographia conservanda',
        'abbreviation': 'orth. cons.',
        'definition': '保留拼法',
        'status': 'accepted',
        'group': ['plant'],
    },
    {
        'type': '地位標註(status)',
        'name': 'nomen oblitum',
        'abbreviation': 'nom. obl.',
        'definition': '被遺忘名',
        'status': 'not-accepted',
        'group': ['animal'],
    },
    {
        'type': '地位標註(status)',
        'name': 'nomen regiciciendum',
        'abbreviation': 'nom. rej.',
        'definition': '廢棄名',
        'status': 'not-accepted',
        'group': ['plant', 'bacteria'],
    },
    {
        'type': '地位標註(status)',
        'name': 'nomen illegitimum',
        'abbreviation': 'nom. illeg.',
        'definition': '不合法名。經正當發表、但不合法規之名稱。',
        'status': 'not-accepted',
        'group': ['plant'],
    },
    {
        'type': '地位標註(status)',
        'name': 'nomen invalid',
        'abbreviation': 'nom. inval.',
        'definition': '不正當名。非經正當發表之名稱。',
        'status': 'not-accepted',
        'group': ['plant'],
    },
    {
        'type': '地位標註(status)',
        'name': 'unavailable',
        'abbreviation': 'unavailable',
        'definition': '不適用。非經正當發表之名稱。',
        'status': 'not-accepted',
        'group': ['animal'],
    },
    {
        'type': '處理標註(treatment)',
        'name': 'synonymum novum',
        'abbreviation': 'syn. nov.',
        'definition': '新同物異名',
        'status': 'not-accepted',
        'group': ['animal', 'plant', 'bacteria'],
    },
    {
        'type': 'description',
        'name': 'ex errore',
        'abbreviation': 'ex errore',
        'definition': '錯誤發表',
        'status': 'not-accepted',
        'group': ['animal', 'plant', 'bacteria'],
    },
    {
        'type': 'description',
        'name': 'nomen abortivum',
        'abbreviation': 'nom. abort.',
        'definition': 'illegitimate name的前用法',
        'status': 'not-accepted',
        'group': ['plant'],
    },
    {
        'type': 'description',
        'name': 'nomen alternativum',
        'abbreviation': 'nom. alt.',
        'definition': '替換名。一作者同時對同一分類群依據相同模式發表可做替換的兩個或多個名稱，1953年以前發表則皆為合法，之後則皆不合法。',
        'status': 'not-accepted',
        'group': ['plant'],
    },
    {
        'type': 'description',
        'name': 'nomen ambiguum',
        'abbreviation': 'nom. ambig.',
        'definition': '模糊不清之名。無法認定為何分類群的名字。',
        'status': 'not-accepted',
        'group': ['plant', 'bacteria'],
    },
    {
        'type': 'description',
        'name': 'nomen confusum',
        'abbreviation': 'nom. confus.',
        'definition': '名稱混淆，命名是基於混菌的培養。',
        'status': 'not-accepted',
        'group': ['bacteria'],
    },
    {
        'type': 'description',
        'name': 'nomen dubium',
        'abbreviation': 'nom. dub.',
        'definition': '疑問名。非正式的用法。',
        'status': 'not-accepted',
        'group': ['animal', 'plant', 'bacteria'],
    },
    {
        'type': 'description',
        'name': 'nomen erratum',
        'abbreviation': 'nom. err.',
        'definition': '命名錯誤。A name given in error.',
        'status': 'not-accepted',
        'group': ['animal', 'plant', 'bacteria'],
    },
    {
        'type': 'description',
        'name': 'nomen manuscriptum',
        'abbreviation': 'nom. manuscriptum',
        'definition': '僅出現在手稿的名稱。',
        'status': 'not-accepted',
        'group': ['animal', 'plant', 'bacteria'],
    },
    {
        'type': 'description',
        'name': 'nomen monstrositatum',
        'abbreviation': 'nom. monstr.',
        'definition': '基於畸形個體命名的名稱。',
        'status': 'not-accepted',
        'group': ['animal'],
    },
    {
        'type': 'description',
        'name': 'nomen periculosum',
        'abbreviation': 'nom. peric.',
        'definition': '名稱可能導致人身或經濟危害。',
        'status': 'not-accepted',
        'group': ['bacteria'],
    },
    {
        'type': 'description',
        'name': 'nomen nudum',
        'abbreviation': 'nom. nud.',
        'definition': '裸名。名稱被發表時未與充分的文字記述一起發表。',
        'status': 'not-accepted',
        'group': ['animal', 'plant', 'bacteria'],
    },
    {
        'type': 'description',
        'name': 'nomen perplexum',
        'abbreviation': 'nom. perp.',
        'definition': '名稱相似而令人困惑。',
        'status': 'not-accepted',
        'group': ['bacteria'],
    },
    {
        'type': 'description',
        'name': 'nomen superfluum',
        'abbreviation': 'nom. superfl.',
        'definition': '多餘名。較晚針對同一標本做的命名。',
        'status': 'not-accepted',
        'group': ['plant'],
    },
    {
        'type': 'description',
        'name': 'pro specie',
        'abbreviation': 'pro. sp.',
        'definition': '名稱發表時以種發表。',
        'status': 'not-accepted',
        'group': ['animal', 'plant', 'bacteria'],
    },
    {
        'type': '拼法標註(orthographic)',
        'name': 'corrigendum',
        'abbreviation': 'corrig.',
        'definition': '拼法修正',
        'status': 'accepted',
        'group': ['animal'],
    },
    {
        'type': 'description',
        'name': 'nomen suppressum',
        'abbreviation': 'nom. supp.',
        'definition': '抑制名。名稱被抑制而不能使用。',
        'status': 'not-accepted',
        'group': ['animal'],
    },
    {
        'type': 'description',
        'name': 'pro hybrida',
        'abbreviation': 'pro. hybr.',
        'definition': '名稱發表時以雜交種發表。',
        'status': 'not-accepted',
        'group': ['animal', 'plant', 'bacteria'],
    },
    {
        'type': 'description',
        'name': 'pro synonymo',
        'abbreviation': 'pro. syn.',
        'definition': '名稱發表時以同物異名發表。As synonym.',
        'status': 'not-accepted',
        'group': ['animal', 'plant', 'bacteria'],
    },
    {
        'type': '拼法標註(orthographic)',
        'name': 'orthographical variant',
        'abbreviation': 'orth. var.',
        'definition': '拼法變異',
        'status': 'not-accepted',
        'group': ['plant'],
    },
    {
        'type': '拼法標註(orthographic)',
        'name': 'sic',
        'abbreviation': '',
        'definition': '原始拼法',
        'status': 'not-accepted',
        'group': ['animal'],
    },
    {
        'type': '未決標註(undetermined)',
        'name': '?',
        'abbreviation': '?',
        'definition': '未確定分類群',
        'status': 'undetermined',
        'group': ['animal', 'plant', 'bacteria'],
    },
    {
        'type': '誤用標註(misapplied)',
        'name': 'auctorum non',
        'abbreviation': 'auct. non',
        'definition': '非指auct. non後方人名所命名的分類群。通常用於錯誤鑑定的引用。',
        'status': 'misapplied',
        'group': ['plant'],
    },
    {
        'type': '誤用標註(misapplied)',
        'name': 'nec',
        'abbreviation': 'nec',
        'definition': '非指nec後方人名所命名的分類群。',
        'status': 'misapplied',
        'group': ['animal'],
    },
];
