export default [
    {'id': 1, 'name': '甲蟲類', 'display': {'en-us': 'Beetles', 'zh-tw': '甲蟲類'}},
    {'id': 2, 'name': '蛾類', 'display': {'en-us': 'Moths', 'zh-tw': '蛾類'}},
    {'id': 3, 'name': '蝶類', 'display': {'en-us': 'Butterflies', 'zh-tw': '蝶類'}},
    {'id': 4, 'name': '蜻蛉類', 'display': {'en-us': 'Dragonflies', 'zh-tw': '蜻蛉類'}},
    {'id': 5, 'name': '其他昆蟲', 'display': {'en-us': 'Other Insects', 'zh-tw': '其他昆蟲'}},
    {'id': 6, 'name': '蜘蛛', 'display': {'en-us': 'Spiders', 'zh-tw': '蜘蛛'}},
    {'id': 7, 'name': '魚類', 'display': {'en-us': 'Fishes', 'zh-tw': '魚類'}},
    {'id': 8, 'name': '兩棲類', 'display': {'en-us': 'Amphibians', 'zh-tw': '兩棲類'}},
    {'id': 9, 'name': '爬蟲類', 'display': {'en-us': 'Reptiles', 'zh-tw': '爬蟲類'}},
    {'id': 10, 'name': '鳥類', 'display': {'en-us': 'Birds', 'zh-tw': '鳥類'}},
    {'id': 11, 'name': '哺乳類', 'display': {'en-us': 'Mammals', 'zh-tw': '哺乳類'}},
    {'id': 12, 'name': '蝸牛與貝類', 'display': {'en-us': 'Snails & Shells', 'zh-tw': '蝸牛與貝類'}},
    {'id': 13, 'name': '蝦蟹類', 'display': {'en-us': 'Crustaceans', 'zh-tw': '蝦蟹類'}},
    {'id': 14, 'name': '被子植物', 'display': {'en-us': 'Angiosperms', 'zh-tw': '被子植物'}},
    {'id': 15, 'name': '裸子植物', 'display': {'en-us': 'Gymnosperms', 'zh-tw': '裸子植物'}},
    {'id': 16, 'name': '蕨類植物', 'display': {'en-us': 'Ferns', 'zh-tw': '蕨類植物'}},
    {'id': 17, 'name': '苔蘚植物', 'display': {'en-us': 'Mosses', 'zh-tw': '苔蘚植物'}},
    {'id': 18, 'name': '藻類', 'display': {'en-us': 'Algae', 'zh-tw': '藻類'}},
    {'id': 19, 'name': '真菌', 'display': {'en-us': 'Fungi', 'zh-tw': '真菌'}},
    {'id': 20, 'name': '病毒', 'display': {'en-us': 'Viruses', 'zh-tw': '病毒'}},
    {'id': 21, 'name': '細菌', 'display': {'en-us': 'Bacteria', 'zh-tw': '細菌'}}
];