export default [
    {'id': 2, 'name': '南投縣', 'display': {'en-us': 'Nantou County', 'zh-tw': '南投縣'}},
    {'id': 19, 'name': '嘉義市', 'display': {'en-us': 'Chiayi City', 'zh-tw': '嘉義市'}},
    {'id': 7, 'name': '嘉義縣', 'display': {'en-us': 'Chiayi County', 'zh-tw': '嘉義縣'}},
    {'id': 20, 'name': '基隆市', 'display': {'en-us': 'Keelung City', 'zh-tw': '基隆市'}},
    {'id': 11, 'name': '宜蘭縣', 'display': {'en-us': 'Yilan County', 'zh-tw': '宜蘭縣'}},
    {'id': 8, 'name': '屏東縣', 'display': {'en-us': 'Pingtung County', 'zh-tw': '屏東縣'}},
    {'id': 15, 'name': '彰化縣', 'display': {'en-us': 'Changhua County', 'zh-tw': '彰化縣'}},
    {'id': 6, 'name': '新北市', 'display': {'en-us': 'New Taipei City', 'zh-tw': '新北市'}},
    {'id': 10, 'name': '新竹市', 'display': {'en-us': 'Hsinchu City', 'zh-tw': '新竹市'}},
    {'id': 17, 'name': '新竹縣', 'display': {'en-us': 'Hsinchu County', 'zh-tw': '新竹縣'}},
    {'id': 3, 'name': '桃園市', 'display': {'en-us': 'Taoyuan County', 'zh-tw': '桃園市'}},
    {'id': 21, 'name': '澎湖縣', 'display': {'en-us': 'Penghu County', 'zh-tw': '澎湖縣'}},
    {'id': 14, 'name': '臺中市', 'display': {'en-us': 'Taichung City', 'zh-tw': '臺中市'}},
    {'id': 18, 'name': '臺北市', 'display': {'en-us': 'Taipei City', 'zh-tw': '臺北市'}},
    {'id': 4, 'name': '臺南市', 'display': {'en-us': 'Tainan City', 'zh-tw': '臺南市'}},
    {'id': 1, 'name': '臺東縣', 'display': {'en-us': 'Taitung County', 'zh-tw': '臺東縣'}},
    {'id': 16, 'name': '花蓮縣', 'display': {'en-us': 'Hualien County', 'zh-tw': '花蓮縣'}},
    {'id': 13, 'name': '苗栗縣', 'display': {'en-us': 'Miaoli County', 'zh-tw': '苗栗縣'}},
    {'id': 22, 'name': '連江縣', 'display': {'en-us': 'Lienchiang County', 'zh-tw': '連江縣'}},
    {'id': 12, 'name': '金門縣', 'display': {'en-us': 'Kinmen County', 'zh-tw': '金門縣'}},
    {'id': 5, 'name': '雲林縣', 'display': {'en-us': 'Yunlin County', 'zh-tw': '雲林縣'}},
    {'id': 9, 'name': '高雄市', 'display': {'en-us': 'Kaohsiung City', 'zh-tw': '高雄市'}},
];